import React from "react";

const GlobalContext = React.createContext({
  monthIndex: 0,
  setMonthIndex: (i) => {},
  daySeeMore: 0,
  setDaySeeMore: (i) => {},
  smallCalendarMonth: 0,
  setSmallCalendarMonth: (i) => {},
  daySelected: null,
  setDaySelected: (i) => {},
  showEventModal: false,
  setShowEventModal: (i) => {},
  showSeeMoreModal: false,
  setShowSeeMoreModal: (i) => {},
  showConfirmModal: false,
  setShowConfirmModal: (i) => {},
  events: [],
  setEvents: (i) => {},
  doctors: [],
  setDoctors: (i) => {},
  user: [],
  setUser: (i) => {},
  selectedEvent: null,
  setSelectedEvent: () => {},
  colors: [],
  setColors: () => {},
  updateColor: () => {},
  filteredEvents: [],
  idEvents: 0,
  setIdEvents: (i) => {},
  isAuth: false,
  setIsAuth: (i) => {},
  username: null,
  setUsername: (i) => {},
  password: null,
  setPassword: (i) => {},
  userAuth: [],
  setUserAuth: (i) => {},
});
export default GlobalContext;
